FLAGS = -Wall -Werror -Wextra
SOURCE = life.c
all:
	gcc $(FLAGS) $(SOURCE) && ./a.out
life1:
	gcc $(FLAGS) $(SOURCE) && ./a.out < 1.txt

life2:
	gcc $(FLAGS) $(SOURCE) && ./a.out < 2.txt

life3:
	gcc $(FLAGS) $(SOURCE) && ./a.out < 3.txt

life4:
	gcc $(FLAGS) $(SOURCE) && ./a.out < 4.txt

life5:
	gcc $(FLAGS) $(SOURCE) && ./a.out < 5.txt

clean:
	rm -rf ./a.out
